name: Jest

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened]

jobs:
  source:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update System
        run: sudo apt-get update
      - name: Install
        run: npm install
      - name: Test
        run: npm run test

        env:
          CI: true
